export const ENABLE_ENTER_KEY = 'ENABLE_ENTER_KEY';
export const DISABLE_ENTER_KEY = 'DISABLE_ENTER_KEY';
export const SEND_BUTTON_CLICK = 'SEND_BUTTON_CLICK';

// starr users
export const HIGH_LIGHT_PERSON = 'HIGH_LIGHT_PERSON';
export const REMOVE_STAR = 'REMOVE_STAR';

// mute user
export const MUTE_PERSON = 'MUTE_PERSON';
export const UNMUTE_PERSON = 'UNMUTE_PERSON';

// show the last message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

// reply message
export const IS_REPLY = 'IS_REPLY';
export const DISABLE_REPLY_MESSAGE = 'DISABLE_REPLY_MESSAGE';
export const IS_MESSAGE_REPLY_SENT = 'IS_MESSAGE_REPLY_SENT';
export const SET_CURRENT_REPLY_INDEX = 'SET_CURRENT_REPLY_INDEX';

//add chat
export const IS_ADD_CHAT_MESSAGE = 'IS_ADD_CHAT_MESSAGE';
export const REMOVE_CHAT_MESSAGE = 'REMOVE_CHAT_MESSAGE';
export const GET_USER_ID = 'GET_USER_ID';

// User Home Page
//reaction on post
export const GET_REACTION_ON_POST = 'GET_REACTION_ON_POST';
export const GET_REACTION_IN_COMMENT_ON_POST = 'GET_REACTION_IN_COMMENT_ON_POST';
export const GET_REACTION_RESPONSE_COMMENTS = 'GET_REACTION_RESPONSE_COMMENTS';
export const ADD_NEW_POSTS = 'ADD_NEW_POSTS';
export const POST_SETTINGS_PRIVACY = 'POST_SETTINGS_PRIVACY';
export const COMMENT_PRIVACY = 'COMMENT_PRIVACY';
export const SAVE_PRIVACY_SELECTED = 'SAVE_PRIVACY_SELECTED';

// comment on post
export const ADD_COMMENT = 'ADD_COMMENT';
export const REPLY_COMMENTS = 'REPLY_COMMENTS';
export const HIDE_COMMENT = 'HIDE_COMMENT';

// sign up account
export const SAVE_ACCOUNT_SIGNUP = 'SAVE_ACCOUNT_SIGNUP';
export const UPDATE_ACCOUNT_INFORMATION = 'UPDATE_ACCOUNT_INFORMATION';
export const USER_LOGGED_IN_INFORMATION = 'USER_LOGGED_IN_INFORMATION';
export const GET_DAY = 'GET_DAY';
export const GET_MONTH = 'GET_MONTH';
export const GET_YEAR = 'GET_YEAR';
export const GET_BIRTH_DATE = 'GET_BIRTH_DATE';

// user photo
export const PHOTO_VIEWING_RIGHTS = 'PHOTO_VIEWING_RIGHTS';
export const SET_SELECTED_FILTER_INDEX = 'SET_SELECTED_FILTER_INDEX';
export const SET_SELECTED_IMAGE_ROTATION_ANGLE = 'SET_SELECTED_IMAGE_ROTATION_ANGLE';

export const SET_SELECTED_FILTER_INDEX_BG = 'SET_SELECTED_FILTER_INDEX_BG';
export const SET_SELECTED_BG_ROTATION_ANGLE = 'SET_SELECTED_BG_ROTATION_ANGLE';
export const HIDE_MODAL = 'HIDE_MODAL';
